name: "General Issue"
description: File any issue
title: "<issue_type>: short description"
projects: ["zama-ai/35"] # blokchain division project
type: task
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: |
        Please describe the issue in detail.
        Replace the <issue_type> placeholder from the title using a Conventional Commit-style prefix (e.g., `fix`, `feat`).
    validations:
      required: true
